name: Tests

on: [push, pull_request]
concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  stylua:
    name: Stylua
    runs-on: ubuntu-latest

    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.pull_request.head.repo.fork == true)

    steps:
      - uses: actions/checkout@v4
      - uses: JohnnyMorganz/stylua-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          version: latest
          args: --check .

  tests:
    name: tests
    runs-on: ${{ matrix.os }}

    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.pull_request.head.repo.fork == true)

    strategy:
      matrix:
        os: [ubuntu-latest, macos-14]
        nvim-version: [v0.8.3, v0.9.5, v0.10.3]
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - name: thing
        if: matrix.os == "ubuntu-latest"
        run: sudo apt-get install libc6-dev
      - name: Run nvim-test tests
        run: nix develop -c just test ${{ matrix.nvim-version }}
